language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: UCe4Ys2hjJLfxX00p6ddS+PKrreig3WK4uS2cq01I4b0p8OYMC0urNJQBmAI9bUOY1k4mcSqwBl0fyYNVPnqCym7KxtcwzQEwp2TM5Fomh0B4Hz8Qzs93VXn9uKE4gNO3rE+bSwhUlm+vDhPNAYO+HPrsVXRnelm5qWiYohCsBm4mKpzLI9UqB5LmJrkqk98uWOA5JRsVCf1W8ekbgD8HB3uQmcBDkYFRw2h5U1AwXkjq/mNxT/+ix5ruYRQwdkSvMhaqJFi1xZQKoqbEI9wXMUtSH/eyv/kiBvoNK/1pTTnKqXSb+3xSmig3Tv9hf2SHzpg2r9CehMMJ1jHUzej6FsVNWkhxe6XdPlxBunE2fWmOIxjlQ7zgzwvrKUrNVeCJL6sY0kxAANdWOvpud+UxkDx/+YdOzdRJ72YmWL4Vzr5PsEMGETDBNs9uIR6ViAN3rRYGmESOAq44tcZyihIP88Zr/tHec1gC4LMnKsgb4+QuSxcUeZCwzFZkRbvs/+1UuBaw+1g7Pp0qWsw56eY8JdTtCSqDM80IEa8nQwY86/wti6bHwiPARk0e4D6XzfCp9daFEyIpUACuMTkpZNFPB7Qd4x2VJM62h59YdTpwCtGRdVI1isZD8ExX2ldfkpVa33fe2J/qG7frXZhCKmZUJixRotG9+JxaDPpJR6gFGM=
  app: travellists
  on:
    repo: AlexWarnes/Travelmate
env:
  global:
    secure: aJU8QptXcUi896QBE7NX84r6XbMOVrKeCOMDeyaT3A19g86ZXdeqn1jvGXFB9aXo4FE6iZUgnjkL9GsOUqZdhCW9xecU3k1r7XjhM7PWIrp5XTv69IggAoJXaj2V23P+IA59YKqIr2C9iPpZ96aaW2UoAAPafBJeKMTa8jk+bVMJb7A4WFQ7P9n7XKwT/DuJFaJDGffCVyvxRlQ7fsAfeREGCKPN0iR6FEvXSDP+/ZmrOFo89V0iximyK7YD6pFAWCDixUzspqr+ouk1/eFSqxiQOT61/9+/zl5cR0Fgt+fZ9nD+f9ctmEWSjJFkVJnGf2bA55/ehxAzjnw5O52qb5IO0ief9TurQkinOd8d7DbVO4n9jsRNuy0ORXJYizxoxqaQD1O60cgjshwmZYYfqdgs7S3+zrB+Dxscrn8LqPzqTaIXT0vKm4ibmjoG+h/XLcE8LJgh6GP7Mc5iuJfTIh8X16ooFFMTiO/5BlASKW55hPWspx2/NnmOVngZlvPBxSTB29NL9TFRGkWyeO7b5lL5pPDFsxaAyYP0jzQLbFBaAlPk11zRjam82hidttWPdC5cLCD4AnoZpekOh+H2GWCZjMCxrlz3PxvzhN4WTcs+0GBNug23iISMtVGTOxq1MzcrJ0BRZBXTEoedIxPbVYgTjHGhcIRZgEmQSuIrlZU=
